Add support for Opensearch_Dashboards
kubedb/dashboard pull request #17
Opened 2022-03-14 07:24 UTC by raihankhan

Signed-off-by: raihankhan <raihan@appscode.com>

2022-03-21 06:21 UTC, kamolhasan requested changes

2022-03-21 06:21 UTC, kamolhasan commented on pkg/distribution/open_search/config.go
> +	dashboardServerPort := edSvc.Spec.Ports[0].Port
Check port before accessing the index

2022-03-21 06:21 UTC, kamolhasan commented on pkg/distribution/open_search/config.go
> +			//databaseCA := ed.dashboard.CertificateFilePath(dapi.ElasticsearchDashboardKibanaConfigDir, databaseCertAlias, dapi.CaCertKey)
remove unwanted comments

2022-03-24 08:43 UTC, raihankhan commented on pkg/distribution/open_search/config.go
> +	dashboardServerPort := edSvc.Spec.Ports[0].Port
added checking

2022-03-24 08:49 UTC, raihankhan commented on pkg/distribution/open_search/config.go
> +			//databaseCA := ed.dashboard.CertificateFilePath(dapi.ElasticsearchDashboardKibanaConfigDir, databaseCertAlias, dapi.CaCertKey)
removed

2022-03-29 12:18 UTC, kamolhasan requested changes

2022-03-29 12:18 UTC, kamolhasan commented on pkg/controllers/dashboard/reconciler.go
> +	return ed.UpdatedElasticsearchDashboard(), err
Remove if not used

2022-03-29 12:18 UTC, kamolhasan commented on pkg/distribution/open_search/config.go
> +	maxOldSpace := (ed.dashboard.Spec.PodTemplate.Spec.Resources.Requests.Memory().Value() * 3) / (4 * 1024 * 1024)
Add comments, references

2022-03-30 04:22 UTC, raihankhan commented on pkg/controllers/dashboard/controller.go
> +			r.Log.Error(err, fmt.Sprintf("Dashboard %s/%s is on deletion", dashboard.Namespace, dashboard.Name))
changed to info

2022-03-30 04:35 UTC, raihankhan commented on pkg/controllers/dashboard/controller.go
> +	// Get database using databaseRef
reconstructed

2022-03-30 04:51 UTC, raihankhan commented on pkg/controllers/dashboard/controller.go
> +	err = r.ensureAuthSecret(ctx, dashboard)
verification added

2022-03-30 04:52 UTC, raihankhan commented on pkg/controllers/dashboard/controller.go
> +	// Ensure clusterIP service (Acts as client service for dashboard instance)
fixed

2022-03-30 04:52 UTC, raihankhan commented on pkg/controllers/dashboard/controller.go
> +
removed

2022-03-30 04:53 UTC, raihankhan commented on pkg/controllers/dashboard/controller.go
> +		if kerr.IsNotFound(err) {
fixed

2022-03-30 04:54 UTC, raihankhan commented on pkg/controllers/dashboard/controller.go
> +			if kmapi.HasCondition(dashboard.Status.Conditions, string(dapi.DashboardConditionServiceReconciled)) &&
reconstructed checking algo

2022-03-30 06:09 UTC, raihankhan commented on pkg/controllers/dashboard/health.go
> +type CertSecrets struct {
reconstructed

2022-03-30 06:16 UTC, raihankhan commented on pkg/controllers/dashboard/reconciler.go
> +	return ed.UpdatedElasticsearchDashboard(), err
removed

2022-03-30 06:59 UTC, raihankhan commented on pkg/distribution/open_search/config.go
> +	maxOldSpace := (ed.dashboard.Spec.PodTemplate.Spec.Resources.Requests.Memory().Value() * 3) / (4 * 1024 * 1024)
added

2022-03-31 10:27 UTC, kamolhasan requested changes

2022-03-31 10:27 UTC, kamolhasan commented on pkg/controllers/dashboard/health.go
> +		crt, _ := tls.X509KeyPair(certSecret.Data[core.TLSCertKey], certSecret.Data[core.TLSPrivateKeyKey])
Handle error

2022-03-31 10:27 UTC, kamolhasan commented on pkg/controllers/dashboard/health.go
> +			IdleConnTimeout: time.Second * 5,
Keep it 3 second

2022-03-31 10:29 UTC, kamolhasan commented on pkg/controllers/dashboard/controller.go
> +	esName := dashboard.Spec.DatabaseRef.Name
Check pointer

2022-03-31 10:39 UTC, kamolhasan approved these changes
LGTM!

2022-03-31 10:40 UTC, merged